### PR TITLE
Added isAdmin property to check whether the logged in user is admin or not

### PR DESCRIPTION
**Pull request by ramyakrishnai**
Added isAdmin property to check whether the logged in user is admin or not.

We wanted to show one button to user is logged in as admin in wordpress. So, to check if the logged in user is admin or not added this property.

### CODE REVIEW

**Review by circlecube — COMMENTED** [review]
Can we have a description added to the PR so that we can document what the intended use case for this feature is?

**Comment by wpscholar** [comment]
@ramyakrishnai Just a heads up, but the `is_admin()` function just checks to see if you're in the WordPress backend/admin area, it doesn't tell you whether or not the user is logged in or has the administrator role.

**Comment by circlecube** [comment]
Micah is correct, the is_admin is not for checking capabilities but for checking the state of the page.

We should be checking for the user role or capability here. This details the roles and capabilities in WordPress: https://wordpress.org/documentation/article/roles-and-capabilities/

You can see it in action here in the plugin settings controller: https://github.com/bluehost/bluehost-wordpress-plugin/blob/cf4b06e7132d406141b2d50e0eb747417be3f049/inc/RestApi/SettingsController.php#L201

Also, might be good to note that we only display the plugin for admin users already. Or at least users who have the 'manage options' permissions. The admin menu checks that the user has permission before adding the plugin to the admin menu. Thus, adding this check won't have much affect unless we display the plugin to more wp users. See: https://github.com/bluehost/bluehost-wordpress-plugin/blob/cf4b06e7132d406141b2d50e0eb747417be3f049/inc/Admin.php#L86

**Comment by ramyakrishnai** [comment]
Thank you for your suggestions @wpscholar @circlecube, Closing this PR as these changes are no longer required.

**Pull request closed without merging**
