### PR TITLE
Convert this module into a runtime package

### PR DESCRIPTION
**Pull request by ramyakrishnai**
Will address #2

### CODE REVIEW

**Comment by wpscholar** [comment]
Thanks @ramyakrishnai,

Let's hold on merging this just yet. After discussions with @arunshenoy99 about how we'll handle modules moving forward, I think we will stick with the `wp-module-runtime` name. 

Additionally, in the `bootstrap.php` file, this is actually what I had in mind:

```php
if ( function_exists( 'add_action' ) )  {
	add_action(
		'newfold_container_set',
		function ( $container )  {
                        $runtime = new Runtime( $container );
                        $runtime->loadIntoPage( 'admin_enqueue_scripts' );
               }
        );
}
```

**Comment by ramyakrishnai** [comment]
hi @wpscholar ,
I tried the code that is shared here but after addig that, newfoldruntime is not loading in the window object getting an error.


I also tried with this https://github.com/newfold-labs/wp-module-data/blob/main/bootstrap.php#L79-L109 but it is still throiwng the same error

I'm also sharing the error here and also attached a screenshot for your reference


**
Uncaught TypeError: Cannot read properties of undefined (reading 'isJarvis')
    at 4432 (accountCard.js:14:37)
    at a (bootstrap:19:22)
    at 689 (index.js?ver=b922c5eee28c4c013ea5:1:667442)
    at a (bootstrap:19:22)
    at 3400 (index.js?ver=b922c5eee28c4c013ea5:1:657785)
    at a (bootstrap:19:22)
    at 2386 (index.js?ver=b922c5eee28c4c013ea5:1:660941)
    at a (bootstrap:19:22)
    at index.js?ver=b922c5eee28c4c013ea5:1:810445
    at index.js?ver=b922c5eee28c4c013ea5:1:811375
**
Screenshot 2023-09-22 at 5 16 21 PM

Could you please  assist me with this.

Thank you!

**Comment by circlecube** [comment]
These errors look like the runtime object wasn't set up properly so when the app tried to find the `isJarvis` value (I'm sure among others), the app broke.

 We'll still need to use the Wordpress hook to add the code (`add_action`). It looks like that is missing. Looks like the code included in this PR doesn't reflect the suggestion @wpscholar mentioned either.

**Comment by ramyakrishnai** [comment]
Hi @circlecube , I've checked with the @wpscholar suggestion and getting the error as shown above. Like I mean NewfoldRuntime is not getting loaded correctly. So, could you please assist with this ?

Thank you

**Comment by wpscholar** [comment]
@ramyakrishnai We can't assist if your latest code isn't in the PR. Can you push the change anyway so we can pull down and test?

**Comment by ramyakrishnai** [comment]
Hi @wpscholar , I've pushed the code and updated my pr with latest code.

Thank you

**Review by wpscholar — APPROVED** [review]

**Pull request merged**
